global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds
  evaluation_interval: 15s  # Evaluate rules every 15 seconds

scrape_configs:
  - job_name: 'ping-monitoring'
    static_configs:
      - targets: ['localhost:8989']  # Python script's metrics endpoint